### ISSUE TITLE
textfiles vs redirection

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [RagnarGrootKoerkamp/cpp-tutorial#12]
Instead of reading from/ writing to files, one could also use
```bash
./a.out < in-file > out-file
```
which is easier IMO (on Linux), but io from files can still be useful of course.

**Comment by manonverra** [comment]
I have never seen anyone in physics use this. You can add it in the course if you like. Although I know a lot of (physics) students are not familiar with Linux before they start with their thesis or master, so it might be good to say something like "If you have no idea what this is, don't worry, just skip this".

**Comment by JoostHouben** [comment]
This is not Linux specific. Works on Windows just as well. Just means you have to execute the program from the command line, or with a shell script. The advantage is that it makes it easier to change what file it writes to, or to use it in an automated fashion, or to let it communicate with other programs. Of course, you might be right that these aren't common use cases for physics students. But it definitely has its advantages.

**Comment by manonverra** [comment]
Hmm... not sure how this works, but I do not know that some people (also in physics) use scripts (I myself have never used this) so they might use this as well then. Could be a good idea to add this to the course.
