### ISSUE TITLE
New simple+advanced problems

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [RagnarGrootKoerkamp/cpp-tutorial#13]
Divide current problems in two subsections, and add new ones where needed.

**Comment by manonverra** [comment]
We want to divide the exercises in two parts: easy/normal ('opgaven') and more challenging ('verdiepende opgaven'). Probably the second category is not possibile for the first few chapters. The easy exercises should be more focused on learning the language, such that even people who have a lot of trouble with programming/puzzling itself are not restricted by this and can still learn the language. The more challenging exercises should just be fun and should contain a little more thinking and puzzling. Most (or all) of the exercises that we already made will fall into the first category, so the priority is to make more challenging exercises, and for the new chapters to also make the easy exercises.
