### ISSUE TITLE
check Run on failed compilation 

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [RagnarGrootKoerkamp/cpp-tutorial#17]

**Comment by manonverra** [comment]
Last year, in the case of a failed compilation using the run butto, the latest working version was run. This was confusing for some of the participants, so Ragnar was thinking about some ways to fix this. Cloud9 has changed in some ways and I tried to reproduce this now, but with every error I intentionally make the latest working version is not run... So it might be fixed. Would be nice if you guys would check this too, to be sure that it's fixed.

**Comment by JoostHouben** [comment]
A pull request from Ragnar to fix this in cloud9 was accepted: https://github.com/c9/c9.ide.run/pull/6

:)

**Comment by JoostHouben** [comment]
But since he opened this issue 4 days ago, he's apparently getting at something else. Not sure what.

**Comment by manonverra** [comment]
Nice! I actually asked him about this 4 days ago, and what kind of solution we had thought of for this, and then he opened the issue, so I think this is really what he's getting at. He might have forgotten/not seen that it was fixed already.

**Comment by RagnarGrootKoerkamp** [comment]
At the time, this fix wasn't yet merged into the live version of C9, but I just checked and it seems to be working now.
