### ISSUE TITLE
Update example at start of notes

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [RagnarGrootKoerkamp/cpp-tutorial#19]

**Comment by JoostHouben** [comment]
I'd love to contribute, but without a description for these issues, I'm kinda at a loss..

**Comment by manonverra** [comment]
In the first section, 'overzicht', an example is given that they should be able to understand at the end of the course. Since we added a lot of stuff to the course, this example should be changed or replaced by a more difficult example.

**Comment by manonverra** [comment]
Hope they're all clear now :)

**Comment by JoostHouben** [comment]
Thanks! :)
